apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keepalived-operator
  namespace: keepalived-operator
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: keepalived-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
